# 1. Import the NUMPY package under the name np.

In [29]:
import pandas as pd
import numpy as np

# 2. Print the NUMPY version and the configuration.

In [4]:
print(np.version)

<module 'numpy.version' from 'C:\\Users\\Aitor\\anaconda3\\lib\\site-packages\\numpy\\version.py'>


In [24]:
print(np.show_config())

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Aitor/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Aitor/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Aitor/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Aitor/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Aitor/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Aitor/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Aitor/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Aitor/anaconda3\\Library\\include']
None


# 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

# 4. Print a

In [5]:
a = np.random.randint (0, 100, (2, 3, 5))
a

array([[[88, 56, 63, 61, 80],
        [57, 53, 19, 91, 98],
        [25, 66, 94, 32, 61]],

       [[ 9, 71, 66, 33, 59],
        [32, 41, 95, 10,  6],
        [41, 50, 84, 45, 96]]])

In [6]:
a= np.random.rand(2, 3, 5)
a

array([[[0.19389792, 0.48047155, 0.28959608, 0.66976906, 0.11677397],
        [0.78035556, 0.46892518, 0.67497687, 0.18029349, 0.59149689],
        [0.03226652, 0.18564252, 0.36387745, 0.316492  , 0.68719992]],

       [[0.08969287, 0.75051004, 0.91713939, 0.72641103, 0.76199768],
        [0.76015066, 0.83985103, 0.38261121, 0.38230411, 0.51005568],
        [0.4221972 , 0.84379341, 0.23381282, 0.73898199, 0.88841551]]])

In [7]:
a = np.random.randint(low=5, high=100, size=(2, 3, 5))
a

array([[[57, 74, 64, 84, 80],
        [88, 35, 43, 69, 43],
        [68, 72, 23, 55, 78]],

       [[87, 37, 14, 48, 47],
        [82, 77, 62, 58, 72],
        [47, 44, 82, 11, 79]]])

# 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
# Assign the array to variable "b"

# 6. Print b

In [8]:
b = np.random.randint (1, 2, (5, 2, 3))
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

# 7. Do a and b have the same size? How do you prove that in Python code?

In [9]:
print(a.size==b.size) #Yes, a and b have the same size

True


# 8. Are you able to add a and b? Why or why not?

In [10]:
# No, a and b cannot be added because they have the same size but a different shape

# 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [11]:
#b = np.random.randint (1, 2, (5, 2, 3))

c= np.transpose (b, (1,2,0))
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

# 10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [12]:
d= a+c
d
# Now it works because they have the same structure

array([[[58, 75, 65, 85, 81],
        [89, 36, 44, 70, 44],
        [69, 73, 24, 56, 79]],

       [[88, 38, 15, 49, 48],
        [83, 78, 63, 59, 73],
        [48, 45, 83, 12, 80]]])

# 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
print(a)

[[[57 74 64 84 80]
  [88 35 43 69 43]
  [68 72 23 55 78]]

 [[87 37 14 48 47]
  [82 77 62 58 72]
  [47 44 82 11 79]]]


In [14]:
print(d)

[[[58 75 65 85 81]
  [89 36 44 70 44]
  [69 73 24 56 79]]

 [[88 38 15 49 48]
  [83 78 63 59 73]
  [48 45 83 12 80]]]


# 12. Multiply a and c. Assign the result to e.


In [15]:
e= a*c
e

array([[[57, 74, 64, 84, 80],
        [88, 35, 43, 69, 43],
        [68, 72, 23, 55, 78]],

       [[87, 37, 14, 48, 47],
        [82, 77, 62, 58, 72],
        [47, 44, 82, 11, 79]]])

# 13. Does e equal to a? Why or why not?

In [16]:
# They have the same size and shape/structure, but not have the same content

# 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [17]:
d_max= d.max()
d_max

89

In [18]:
d_min= d.min()
d_min

12

In [19]:
d_mean= d.mean()
d_mean

60.333333333333336

# 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [25]:
f = np.empty ((2,3,5), dtype = int)


# 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
# If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
# If a value equals to d_mean, assign 50 to the corresponding value in f.
# Assign 0 to the corresponding value(s) in f for d_min in d.
# Assign 100 to the corresponding value(s) in f for d_max in d.
# In the end, f should have only the following values: 0, 25, 50, 75, and 100.
# Note: you don't have to use Numpy in this question.
"""


In [26]:
x = (d > d_mean) & (d < d_max)
f[x] = 75

x = (d < d_mean) & (d > d_min)
f[x] = 25

x = (d == d_mean)
f[x] = 50

e = (d >= d_max)
f[e] = 100

x = (d <= d_min)
f[x] = 0

In [27]:
print(d)

[[[58 75 65 85 81]
  [89 36 44 70 44]
  [69 73 24 56 79]]

 [[88 38 15 49 48]
  [83 78 63 59 73]
  [48 45 83 12 80]]]


In [28]:
print(f)

[[[ 25  75  75  75  75]
  [100  25  25  75  25]
  [ 75  75  25  25  75]]

 [[ 75  25  25  25  25]
  [ 75  75  75  25  75]
  [ 25  25  75   0  75]]]
