In [2]:
import numpy as np

In [3]:
print(np.__version__)

1.19.2


In [6]:
print(np.show_config())

blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
None


In [54]:
a = np.random.rand(2,3,5)
a

array([[[0.00461077, 0.670361  , 0.47566384, 0.19614691, 0.34137439],
        [0.84286962, 0.86596232, 0.7327816 , 0.286432  , 0.34663628],
        [0.4553677 , 0.87115929, 0.44712488, 0.28713996, 0.41676244]],

       [[0.72388289, 0.23958634, 0.89799645, 0.33457552, 0.29035718],
        [0.68787049, 0.13251995, 0.68330636, 0.31728284, 0.03896933],
        [0.42900627, 0.51650404, 0.88588548, 0.76091127, 0.39264133]]])

In [55]:
b = np.ones((5,2,3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [26]:
if (a.shape == b.shape):
    print('a and b have the same size')
else:
    print('a and b does not have the same size')

a and b does not have the same size


In [58]:
c = np.transpose(b, (1, 2, 0))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [59]:
d = a + c

In [61]:
print(a)

[[[0.00461077 0.670361   0.47566384 0.19614691 0.34137439]
  [0.84286962 0.86596232 0.7327816  0.286432   0.34663628]
  [0.4553677  0.87115929 0.44712488 0.28713996 0.41676244]]

 [[0.72388289 0.23958634 0.89799645 0.33457552 0.29035718]
  [0.68787049 0.13251995 0.68330636 0.31728284 0.03896933]
  [0.42900627 0.51650404 0.88588548 0.76091127 0.39264133]]]


In [62]:
print(d)

[[[1.00461077 1.670361   1.47566384 1.19614691 1.34137439]
  [1.84286962 1.86596232 1.7327816  1.286432   1.34663628]
  [1.4553677  1.87115929 1.44712488 1.28713996 1.41676244]]

 [[1.72388289 1.23958634 1.89799645 1.33457552 1.29035718]
  [1.68787049 1.13251995 1.68330636 1.31728284 1.03896933]
  [1.42900627 1.51650404 1.88588548 1.76091127 1.39264133]]]


In [63]:
e = a * c

In [64]:
print(e)

[[[0.00461077 0.670361   0.47566384 0.19614691 0.34137439]
  [0.84286962 0.86596232 0.7327816  0.286432   0.34663628]
  [0.4553677  0.87115929 0.44712488 0.28713996 0.41676244]]

 [[0.72388289 0.23958634 0.89799645 0.33457552 0.29035718]
  [0.68787049 0.13251995 0.68330636 0.31728284 0.03896933]
  [0.42900627 0.51650404 0.88588548 0.76091127 0.39264133]]]


In [66]:
d_max = d.max()
d_max

1.897996451565246

In [67]:
d_min = d.min()
d_min

1.0046107657814631

In [68]:
d_mean = d.mean()
d_mean

1.485722958523967

In [75]:
f = np.empty([2, 3, 5])
f

array([[[0.00461077, 0.670361  , 0.47566384, 0.19614691, 0.34137439],
        [0.84286962, 0.86596232, 0.7327816 , 0.286432  , 0.34663628],
        [0.4553677 , 0.87115929, 0.44712488, 0.28713996, 0.41676244]],

       [[0.72388289, 0.23958634, 0.89799645, 0.33457552, 0.29035718],
        [0.68787049, 0.13251995, 0.68330636, 0.31728284, 0.03896933],
        [0.42900627, 0.51650404, 0.88588548, 0.76091127, 0.39264133]]])

In [80]:
for i in np.nditer(d):
    if (i > d_min) & (i < d_mean):
        f.insert(25)
    elif (i > d_mean) & (i <  d_max):
        f.insert(75)
    elif (i == d_mean):
        f.insert(50)
    elif (i == d_min):
        f.insert(0)
    elif (i == d_max):
        f.insert(100)
        
print(f)

AttributeError: 'numpy.ndarray' object has no attribute 'insert'